- build.gradle
- src/main/java/com/sequenceiq/cloudbreak/shell/CloudbreakShell.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/BasicCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/BlueprintCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/ClusterCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/RecipeCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/model/CloudbreakContext.java
@keyki 
- add/list/show/delete recipe
- cluster create with recipe in context
- rest-client-version is set to 0.2.27 that will be available after that PR is merged
> support recipes

- src/main/java/com/sequenceiq/cloudbreak/shell/model/CloudbreakContext.java
@martonsereg just for you :dancer:
> CLOUD-340 fixed blueprint selection

- config/checkstyle/checkstyle.xml
- src/main/java/com/sequenceiq/cloudbreak/shell/CloudbreakShell.java
> CLOUD-435: Printing stack trace instead of hiding it

- src/main/java/com/sequenceiq/cloudbreak/shell/commands/RecipeCommands.java
> recipe select command available after recipe is added

- src/main/java/com/sequenceiq/cloudbreak/shell/commands/ClusterCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/CredentialCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/TemplateCommands.java
@biharitomi or @schfeca75 pls check this pr
> Added cluster and stack put to the shell

- src/main/java/com/sequenceiq/cloudbreak/shell/model/AwsInstanceType.java
- src/main/java/com/sequenceiq/cloudbreak/shell/model/AzureInstanceType.java
> CLOUD-435 fixed instancetypes

- src/main/java/com/sequenceiq/cloudbreak/shell/model/AwsInstanceType.java
> CLOUD-451: Remove aws instancetypes which does not support HVM amis

- build.gradle
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/ClusterCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/model/AdjustmentType.java
- src/main/java/com/sequenceiq/cloudbreak/shell/model/OnFailureAction.java
> CLOUD-422 added failure handling support

- src/main/java/com/sequenceiq/cloudbreak/shell/CloudbreakShell.java
- src/main/resources/logback.xml
> CLOUD-422 version added

- build.gradle
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/BlueprintCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/CredentialCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/InstanceGroupCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/RecipeCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/TemplateCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/completion/InstanceGroupTemplateName.java
- src/main/java/com/sequenceiq/cloudbreak/shell/configuration/ConverterConfiguration.java
- src/main/java/com/sequenceiq/cloudbreak/shell/converter/InstanceGroupTemplateNameConverter.java
- src/main/java/com/sequenceiq/cloudbreak/shell/model/CloudbreakContext.java
- src/test/java/com/sequenceiq/cloudbreak/shell/commands/BlueprintCommandsTest.java
- src/test/java/com/sequenceiq/cloudbreak/shell/commands/CredentialCommandsTest.java
- src/test/java/com/sequenceiq/cloudbreak/shell/commands/InstanceGroupCommandsTest.java
- src/test/java/com/sequenceiq/cloudbreak/shell/commands/RecipeCommandsTest.java
- src/test/java/com/sequenceiq/cloudbreak/shell/commands/StackCommandsTest.java
- src/test/java/com/sequenceiq/cloudbreak/shell/commands/TemplateCommandsTest.java
> CLOUD-484 select resources by name

- build.gradle
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/ClusterCommands.java
Needed if sequenceiq/cloudbreak#490 is merged
> hostgroup domain chages

- build.gradle
- config/checkstyle/checkstyle-suppressions.xml
- src/main/java/com/sequenceiq/cloudbreak/shell/CloudbreakShell.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/TemplateCommands.java
> CLOUD-433 encrypted volume possibility added

- build.gradle
- src/main/java/com/sequenceiq/cloudbreak/shell/CloudbreakShell.java
- src/main/java/com/sequenceiq/cloudbreak/shell/VersionedApplication.java
> CLOUD-515 added version check

- src/main/java/com/sequenceiq/cloudbreak/shell/CloudbreakShell.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/ClusterCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/HostGroupCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/InstanceGroupCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/TemplateCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/converter/HostGroupConverter.java
- src/main/java/com/sequenceiq/cloudbreak/shell/model/CloudbreakContext.java
- src/main/java/com/sequenceiq/cloudbreak/shell/model/Hints.java
- src/test/java/com/sequenceiq/cloudbreak/shell/commands/InstanceGroupCommandsTest.java
@martonsereg or @matyix or @biharitomi
> CLOUD-518 refactored shell based on hostgroup modifications

- build.gradle
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/ClusterCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/HostGroupCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java
need to update the rest client version before merge
> CLOUD-523 upscale and downscale can be in one request

- build.gradle
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/CredentialCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/TemplateCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/model/Region.java
> CLOUD-559 added openstack support

- src/main/java/com/sequenceiq/cloudbreak/shell/commands/ClusterCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/HostGroupCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/model/Hints.java
- src/test/java/com/sequenceiq/cloudbreak/shell/commands/StackCommandsTest.java
@biharitomi 
depends on: https://github.com/sequenceiq/cloudbreak/pull/598
> CLOUD-680 fixed cluster commands

- build.gradle
- src/main/java/com/sequenceiq/cloudbreak/shell/CloudbreakShell.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/BasicCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/InstanceGroupCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/NetworkCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/TemplateCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/completion/NetworkId.java
- src/main/java/com/sequenceiq/cloudbreak/shell/completion/NetworkName.java
- src/main/java/com/sequenceiq/cloudbreak/shell/configuration/ConverterConfiguration.java
- src/main/java/com/sequenceiq/cloudbreak/shell/converter/NetworkIdConverter.java
- src/main/java/com/sequenceiq/cloudbreak/shell/converter/NetworkNameConverter.java
- src/main/java/com/sequenceiq/cloudbreak/shell/model/CloudbreakContext.java
- src/main/java/com/sequenceiq/cloudbreak/shell/model/Hints.java
> CLOUD-658 migrate network abstraction

- src/main/java/com/sequenceiq/cloudbreak/shell/commands/ClusterCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/model/StatusRequest.java
> CLOUD-755 added start stop to shell

- src/main/java/com/sequenceiq/cloudbreak/shell/commands/ClusterCommands.java
@keyki changed stack def and clarified the package manager dependency on OS
> changed desc

- build.gradle
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/CredentialCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/TemplateCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/model/Region.java
> CLOUD-620 change gcc to gcp

- build.gradle
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java
> CLOUD-785 disk per storage on Azure

- README.md
Please find a proposal for [issue #82](https://github.com/sequenceiq/cloudbreak-shell/issues/82) as well as example for other supported cloud platforms.
> Fix#82: wrong AWS example and added examples for GCP, Openstack & Azure

- build.gradle
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java
@oleewere or @keyki please take a look!
> CLOUD-836 add support for dedicated instances on AWS

- build.gradle
- src/main/java/com/sequenceiq/cloudbreak/shell/CloudbreakShell.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/NetworkCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/SecurityGroupCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/completion/SecurityGroupId.java
- src/main/java/com/sequenceiq/cloudbreak/shell/completion/SecurityGroupName.java
- src/main/java/com/sequenceiq/cloudbreak/shell/configuration/ConverterConfiguration.java
- src/main/java/com/sequenceiq/cloudbreak/shell/converter/SecurityGroupIdConverter.java
- src/main/java/com/sequenceiq/cloudbreak/shell/converter/SecurityGroupNameConverter.java
- src/main/java/com/sequenceiq/cloudbreak/shell/model/CloudbreakContext.java
- src/main/java/com/sequenceiq/cloudbreak/shell/model/Hints.java
> CLOUD-872 select security group when creating stack

- src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/model/CloudbreakContext.java
> CLOUD-969 fixed stack select command

- src/main/java/com/sequenceiq/cloudbreak/shell/commands/ClusterCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java
> CLOUD-969 autocomplete added to downscale and upscale

- build.gradle
- gradle.properties
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/ClusterCommands.java
> CLOUD-41495 Enable security at cluster create

- README.md
Forgotten readme update @keyki
> CLOUD-41495 Readme update with security related options

- gradle.properties
> CLOUD-41495 Update CB client version

- src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/model/CloudbreakContext.java
> CLOUD-42764 Fix cast to implementatio

- gradle.properties
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/ClusterCommands.java
> CLOUD-41495 Remove kerberos related unspecified default values

- gradle.properties
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/CredentialCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/model/CloudbreakContext.java
@keyki or @martonsereg or @akanto
> CLOUD-42308 added azure rm support

- .gitignore
- README.md
> CLOUD-42308 added azure rm to readme

- src/main/java/com/sequenceiq/cloudbreak/shell/model/Region.java
> CLOUD-43501 added frankfurt

- README.md
> Extend read with example command file

- README.md
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/RecipeCommands.java
- src/test/java/com/sequenceiq/cloudbreak/shell/commands/RecipeCommandsTest.java
@martonsereg don’t merge till client version is updated
> CLOUD-43504 Strore recipe in Consul

- README.md
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/ClusterCommands.java
@keyki 
simple wasb from shell
> CLOUD-47753 simple wasb fs filesystem setup from cli

- src/main/java/com/sequenceiq/cloudbreak/shell/commands/RecipeCommands.java
> Fix typos in recipe add command

- README.md
- gradle.properties
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/SecurityGroupCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/completion/SecurityRules.java
- src/main/java/com/sequenceiq/cloudbreak/shell/configuration/ConverterConfiguration.java
- src/main/java/com/sequenceiq/cloudbreak/shell/converter/SecurityRulesConverter.java
- src/main/java/com/sequenceiq/cloudbreak/shell/model/Hints.java
> CLOUD-45516: Extend cloudbreak-shell with security group handling

- README.md
> Fix cluster node commands in readme

- src/main/java/com/sequenceiq/cloudbreak/shell/model/AzureInstanceType.java
> CLOUD-45976 Azure D_V2 instance types

- README.md
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/CredentialCommands.java
- src/test/java/com/sequenceiq/cloudbreak/shell/commands/CredentialCommandsTest.java
> CLOUD-46099 removed old azure implementation

- config/checkstyle/checkstyle-suppressions.xml
- config/checkstyle/checkstyle.xml
- gradle.properties
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/completion/StackAvailabilityZone.java
- src/main/java/com/sequenceiq/cloudbreak/shell/configuration/ConverterConfiguration.java
- src/main/java/com/sequenceiq/cloudbreak/shell/converter/StackAvailabilityZoneConverter.java
- src/main/java/com/sequenceiq/cloudbreak/shell/model/Hints.java
- src/main/java/com/sequenceiq/cloudbreak/shell/model/Region.java
> CLOUD-45130 added av zone

- build.gradle
> CLOUD-46423: Set mainClassName prop in build.gradle

- README.md
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/CredentialCommands.java
> CLOUD-46414 fixed command parameters

- src/main/java/com/sequenceiq/cloudbreak/shell/commands/InstanceGroupCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/support/TableRenderer.java
> CLOUD-46816 fixed ig show

- src/main/java/com/sequenceiq/cloudbreak/shell/configuration/ShellConfiguration.java
> CLOUD-43757 fix token parsing issue that is caused by uaa upgrade

- gradle.properties
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/SecurityGroupCommands.java
> CLOUD-46100 security group client change

- src/main/java/com/sequenceiq/cloudbreak/shell/commands/ClusterCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/util/MessageUtil.java
> CLOUD-48036 proper error message for stopping/starting cluster and stack

- src/main/java/com/sequenceiq/cloudbreak/shell/CloudbreakShell.java
- src/main/java/com/sequenceiq/cloudbreak/shell/configuration/ShellConfiguration.java
> CLOUD-48388 validate username password

- src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java
- src/main/java/com/sequenceiq/cloudbreak/shell/exception/ValidationException.java
> CLOUD-48521 CBD Shell: Stack Region typo throws Internal server error

- gradle.properties
> CLOUD-48916 generic platform entities

- gradle.properties
- src/main/java/com/sequenceiq/cloudbreak/shell/commands/CredentialCommands.java
> CLOUD-48917 added openstack support
